"repository":
  "name": "clock"
  "description": "Provides a Clock implementation for PHP"
  "homepage": "https://github.com/ghostwriter/clock"
  "topics": "clock, ghostwriter"
  "private": false
  "has_issues": true
  "has_projects": false
  "has_wiki": false
  "has_downloads": true
  "default_branch": "3.0.x"
  "allow_squash_merge": true
  "allow_merge_commit": true
  "allow_rebase_merge": true
  "delete_branch_on_merge": true
  "enable_automated_security_fixes": true
  "enable_vulnerability_alerts": true
"milestones":
  - "title": "3.3.1"
    "description": "Patch release – targeting 3.3.x branch (semantic version: 3.3.1)"
    "state": "open"
  - "title": "3.0.2"
    "description": "Patch release – targeting 3.0.x branch (semantic version: 3.0.2)"
    "state": "open"
  - "title": "3.0.1"
    "description": "Patch release – targeting 3.0.x branch (semantic version: 3.0.1)"
    "state": "closed"
  - "title": "3.1.0"
    "description": "Minor release – targeting 3.1.x branch (semantic version: 3.1.0)"
    "state": "open"
  - "title": "4.0.0"
    "description": "Major release – targeting 4.0.x branch (semantic version: 4.0.0)"
    "state": "open"
